name : print hello world
on :
  push :
    branches : 
      - test

jobs :
  printAA :
    runs-on : ubuntu-latest
    steps :
      - name: print hi
        run : echo "Helloooo"

      - name: Run multiple commands
        run: |
          echo "Hello"
          date
          uname -a













